# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/incremental stuff',
                'doc_host': 'https://kg.github.io',
                'git_url': 'https://github.com/kg/incremental stuff',
                'lib_path': 'incremental stuff'},
  'syms': {'incremental stuff.core': {'incremental stuff.core.foo': ('core.html#foo', 'incremental stuff/core.py')}}}
